# Site settings
baseurl = "https://tim-christie.com/"
languageCode = "en-au"
title = "Tim Christie"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-15997870-4"
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Tim Christie"
	description = "Personal weblog"
	bio = ""
	# Enter optionally your twitter account
	twitter = ""
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "tim-christie.com"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://twitter.com/tsctalk"
    github   = "https://github.com/timschristie"
    linkedin  = "https://www.linkedin.com/in/timschristie"
